import Head from "next/head"
import { Flex } from "@chakra-ui/react"
import { getProviders, getSession, useSession } from "next-auth/react"
import { useRecoilState } from "recoil"

import Sidebar from "../components/Sidebar"
import Feed from "../components/Feed"
import Login from "../components/Login"
import { modalState } from "../atom/modalAtom"
import { CommentModal } from "../components/CommentModal"
import Widget from "../components/Widget"

export default function Home({ trendingResults, followResults, providers }) {
	const { data: session } = useSession()

	if (!session) return <Login providers={providers} />

	return (
		<div>
			<Head>
				<title>New Twister</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Flex bgGradient="linear(to-r, gray.300, yellow.400, pink.200)" minHeight="100vh" mx="auto" maxW="1500px">
					<Sidebar />
					<Feed />
					<Widget trending={trendingResults} follow={followResults} />
					<CommentModal />
				</Flex>
			</main>
		</div>
	)
}

export const getServerSideProps = async (context) => {
	const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then((res) => res.json())
	const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then((res) => res.json())
	const providers = await getProviders()
	const session = await getSession(context)

	return {
		props: {
			trendingResults,
			followResults,
			providers,
			session,
		},
	}
}
